### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by vivekascoder** [EricLBuehler/kestrel#1]
Does storing function scopes, with Hashmap<Fn, Namespace> is better than doing something like Vec<Hashmap<String, Val>>, to store each scope, because the former won't allow you to have nested scopes inside a function right?

**Comment by EricLBuehler** [comment]
Interesting question! This is actually a quirk of my design - the `Mir` keeps track of all bindings and validates them, with the `CodeGen` only concerning itself with the pointers. The `Mir` makes sure that the `CodeGen` does not generate invalid code by enforcing ownership, scoping, etc. with it's namespaces.

The `CodeGen`, therefore only needs 1 namespace per function.

**Comment by vivekascoder** [comment]
thanks for answering, diving into Mir

**Comment by EricLBuehler** [comment]
Great! Let me know if you have any questions.
