### ISSUE TITLE
Question on strings in llvm ir

### ISSUE THREAD

**Issue by vivekascoder** [EricLBuehler/kestrel#2]
I want to implement c++ std::string like strings into my language, I'm not clear how it's done, can you tell me how should I go about implementing simple string types in my lang.

**Comment by EricLBuehler** [comment]
Hi @vivekascoder, great to hear from you! LLVM does not have a String type. However, it does have an Array type. So, there are the following steps:
1) Allocate the string data on the heap
2) Use GEP 0,0 to get a pointer to it
3) Store that pointer in a struct called `String` with length metadata
4) Done!

See this link: https://mapping-high-level-constructs-to-llvm-ir.readthedocs.io/en/latest/appendix-a-how-to-implement-a-string-type-in-llvm/index.html
