### ISSUE TITLE
Another question.

### ISSUE THREAD

**Issue by vivekascoder** [EricLBuehler/kestrel#3]
why are you not on twitter, or if you're give me the link so that I text you there or Discord.

**Comment by vivekascoder** [comment]
So this is an example of a recursive function in my lang.

```
/**
* calculate sum of fibonacci sequence using tiny lang.
**/

extern fun printf(s: *i8, ...) => usize;

fun fibo(num: usize) => usize {
    if (num == 0) {
        return 0;
    } else {
        if (num == 1) {
            return 1;
        } else {
            return fibo(num - 1) + fibo(num - 2);
        }
    }
}

fun main() => usize {
    printf("%d", fibo(5));
    return 0;
}
```

And my codegen currently emits something like following.

```ll
; ModuleID = './examples/fibonacci.tiny'
source_filename = "fibonacci"

@0 = constant [4 x i8] c"\22%d\00"

declare i32 @printf(ptr, ...)

define i32 @fibo(i32 %0) {
main_fibo_block:
  %1 = icmp eq i32 %0, 0
  br i1 %1, label %2, label %3

2:                                                ; preds = %main_fibo_block
  ret i32 0

3:                                                ; preds = %main_fibo_block
  %4 = icmp eq i32 %0, 1
  br i1 %4, label %5, label %6

5:                                                ; preds = %3
  ret i32 1

6:                                                ; preds = %3
  %7 = sub i32 %0, 1
  %8 = call i32 @fibo(i32 %7)
  %9 = sub i32 %0, 2
  %10 = call i32 @fibo(i32 %9)
  %11 = add i32 %8, %10
  ret i32 %11
}

define i32 @main() {
main_main_block:
  %0 = call i32 @fibo(i32 5)
  %1 = call i32 (ptr, ...) @printf(ptr @0, i32 %0)
  ret i32 0
}

```

It works for smaller values, but when I run the function `@fibo()` for `50` it takes forever, can you help with with potential cause? Thanks

**Comment by vivekascoder** [comment]
> why are you not on twitter, or if you're give me the link so that I text you there or Discord.

In case you don't use any social media platform, give me your mail :)

**Comment by EricLBuehler** [comment]
Looks like you are using a recursive approach - so `fibo(50)` will take a long time. The big-O is `O(Z ^ n)` (where Z is the golden ratio ~1.62). Therefore `fibo(50)` means on the order of `29905476533` operations. How much time did it take? 

Your programming language looks very cool - I especially like the `extern fun` syntax! Here is my reddit: https://www.reddit.com/user/EricBuehler

**Comment by vivekascoder** [comment]
> Looks like you are using a recursive approach - so `fibo(50)` will take a long time. The big-O is `O(Z ^ n)` (where Z is the golden ratio ~1.62). Therefore `fibo(50)` means on the order of `29905476533` operations. How much time did it take?
> 
> Your programming language looks very cool - I especially like the `extern fun` syntax! Here is my reddit: https://www.reddit.com/user/EricBuehler

It's basically infinite loop 😅, thanks for the extern syntax.

**Comment by vivekascoder** [comment]
I texted you on reddit

**Comment by EricLBuehler** [comment]
I don't see it... how did you text it?

**Comment by EricLBuehler** [comment]
Update: I just got it.
